number1 = float(input("Enter num1: "))
number2 = float(input("Enter num2: "))
total = number1 + number2
sub = number1 - number2
multi = number1 * number2
division = number1 / number2
modulus = number1 % number2
exponen = number1**number2
print(number1, '+', number2, '=', total)
print(number1, '-', number2, '=', sub)
print(number1, '*', number2, '=', multi)
print(number1, '/', number2, '=', division)
print(number1, '%', number2, '=', modulus)
print(number1, '^', number2, '=', exponen)
